version: '3'
services:
  pqdb:
    image: 'postgres:9.5'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/parsedata
    ports:
      - 5432:5432
    environment:
    - POSTGRES_PASSWORD=parse
    - POSTGRES_USER=parse
    - POSTGRES_DB=parse
    - PGDATA=/var/lib/postgresql/data/parsedata
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  parse:
    image: 'parseplatform/parse-server:latest'
    environment:
      - PARSE_SERVER_APPLICATION_ID=parse
      - PARSE_SERVER_MASTER_KEY=parse@master123!
      - PARSE_SERVER_DATABASE_URI=postgres://parse:parse@pqdb/parse
      - PARSE_SERVER_MOUNT_PATH=/parse
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY={"classNames":["location","monitor"]}
    ports:
      - '1337:1337'
    links:
      - pqdb
  parse-dashboard:
    image: 'parseplatform/parse-dashboard'
    ports:
      - '4040:4040'
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=/api
      - PARSE_DASHBOARD_MASTER_KEY=parse@master123!
      - PARSE_DASHBOARD_APP_ID=parse
      - PARSE_DASHBOARD_APP_NAME=MyParseApp
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=pwd@admin123!
      - MOUNT_PATH=/dashboard/
    links:
      - parse
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx:/etc/nginx/sites-enabled'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      # letsencrypt will put generated pems under /etc/letsencrypt/live/yourdomain.com, copy them to nginx container. 
      # - '/etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem'
      # - '/etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem'
    links:
      - parse-dashboard
      - parse
      - portainer
volumes:
  portainer_data:
  db-data:
    driver: local
